default_node= "127.0.0.1:9000"

[[my_keys]]
public = "miner/alice.pub.pem"
private = "miner/alice.priv.cbor"

[[contacts]]
name = "Alice"
key = "miner/alice.pub.pem"

[[contacts]]
name = "Bob"
key = "miner/bob.pub.pem"

[fee_config]
fee_type = "Percent"
value = 0.0
