[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
btclib ={ path = "../lib"}
spki = { version = "0.7.3", features = ["pem"] }
tokio = { version = "1.44.1", features = ["full"] }
